# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BuildBack' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BuildBack
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Kingfisher'
  pod 'FirebaseFirestoreSwift'
  target 'BuildBackTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
